### PR TITLE
Update dependencies

### LINKED ISSUE #215: Zoom Oauth endpoint changed?!
We start the oauth dance in https://zoom.us/oauth, but that's a 404 now.

The proper URL is https://zoom.us/oauth/authorize - I don't understand why it's was working before...

The client we use may be obsolete:

https://github.com/iflorespaz/oauth2-zoom/blob/c821c204df75c25de8840a48ae96f2122d6c5e5b/src/Provider/Zoom.php#L56-L59

### PR DESCRIPTION
**Pull request by Nispeon**
( Fix #215 ) Updated dependencies to get the new API endpoint for Zoom.

Changelogs summary:

 - symfony/flex updated from v1.15.3 to v1.16.3 minor
   See changes: symfony/flex@v1.15.3...v1.16.3
   Release notes: https://github.com/symfony/flex/releases/tag/v1.16.3

 - symfony/password-hasher updated from v5.3.7 to v5.3.8 patch
   See changes: symfony/password-hasher@v5.3.7...v5.3.8
   Release notes: https://github.com/symfony/password-hasher/releases/tag/v5.3.8

 - symfony/security-core updated from v5.3.7 to v5.3.8 patch
   See changes: symfony/security-core@v5.3.7...v5.3.8
   Release notes: https://github.com/symfony/security-core/releases/tag/v5.3.8

 - symfony/var-dumper updated from v5.3.7 to v5.3.8 patch
   See changes: symfony/var-dumper@v5.3.7...v5.3.8
   Release notes: https://github.com/symfony/var-dumper/releases/tag/v5.3.8

 - psr/log updated from 1.1.4 to 2.0.0 major
   See changes: php-fig/log@1.1.4...2.0.0
   Release notes: https://github.com/php-fig/log/releases/tag/2.0.0

 - symfony/http-kernel updated from v5.3.7 to v5.3.9 patch
   See changes: symfony/http-kernel@v5.3.7...v5.3.9
   Release notes: https://github.com/symfony/http-kernel/releases/tag/v5.3.9

 - symfony/dependency-injection updated from v5.3.7 to v5.3.8 patch
   See changes: symfony/dependency-injection@v5.3.7...v5.3.8
   Release notes: https://github.com/symfony/dependency-injection/releases/tag/v5.3.8

 - bugsnag/bugsnag updated from v3.26.0 to v3.26.1 patch
   See changes: bugsnag/bugsnag-php@v3.26.0...v3.26.1
   Release notes: https://github.com/bugsnag/bugsnag-php/releases/tag/v3.26.1

 - iflorespaz/oauth2-zoom updated from dev-master@3336760 to dev-master@2a17b1b
   See changes: Nispeon/oauth2-zoom@3336760...2a17b1b

 - symfony/serializer updated from v5.3.4 to v5.3.8 patch
   See changes: symfony/serializer@v5.3.4...v5.3.8
   Release notes: https://github.com/symfony/serializer/releases/tag/v5.3.8

 - symfony/http-client updated from v5.3.7 to v5.3.8 patch
   See changes: symfony/http-client@v5.3.7...v5.3.8
   Release notes: https://github.com/symfony/http-client/releases/tag/v5.3.8

 - php-http/discovery updated from 1.14.0 to 1.14.1 patch
   See changes: php-http/discovery@1.14.0...1.14.1
   Release notes: https://github.com/php-http/discovery/releases/tag/1.14.1

 - symfony/property-info updated from v5.3.7 to v5.3.8 patch
   See changes: symfony/property-info@v5.3.7...v5.3.8
   Release notes: https://github.com/symfony/property-info/releases/tag/v5.3.8

 - symfony/property-access updated from v5.3.7 to v5.3.8 patch
   See changes: symfony/property-access@v5.3.7...v5.3.8
   Release notes: https://github.com/symfony/property-access/releases/tag/v5.3.8

 - symfony/security-http updated from v5.3.7 to v5.3.8 patch
   See changes: symfony/security-http@v5.3.7...v5.3.8
   Release notes: https://github.com/symfony/security-http/releases/tag/v5.3.8

 - symfony/var-exporter updated from v5.3.7 to v5.3.8 patch
   See changes: symfony/var-exporter@v5.3.7...v5.3.8
   Release notes: https://github.com/symfony/var-exporter/releases/tag/v5.3.8

 - symfony/cache updated from v5.3.7 to v5.3.8 patch
   See changes: symfony/cache@v5.3.7...v5.3.8
   Release notes: https://github.com/symfony/cache/releases/tag/v5.3.8

 - symfony/framework-bundle updated from v5.3.7 to v5.3.8 patch
   See changes: symfony/framework-bundle@v5.3.7...v5.3.8
   Release notes: https://github.com/symfony/framework-bundle/releases/tag/v5.3.8

 - phpstan/phpstan updated from 0.12.98 to 0.12.99 patch
   See changes: phpstan/phpstan@0.12.98...0.12.99
   Release notes: https://github.com/phpstan/phpstan/releases/tag/0.12.99

 - monolog/monolog updated from 2.3.2 to 2.3.4 patch
   See changes: Seldaek/monolog@2.3.2...2.3.4
   Release notes: https://github.com/Seldaek/monolog/releases/tag/2.3.4

 - twig/twig updated from v3.3.2 to v3.3.3 patch
   See changes: twigphp/Twig@v3.3.2...v3.3.3
   Release notes: https://github.com/twigphp/Twig/releases/tag/v3.3.3

 - symfony/dotenv updated from v5.3.7 to v5.3.8 patch
   See changes: symfony/dotenv@v5.3.7...v5.3.8
   Release notes: https://github.com/symfony/dotenv/releases/tag/v5.3.8

 - symfony/form updated from v5.3.7 to v5.3.8 patch
   See changes: symfony/form@v5.3.7...v5.3.8
   Release notes: https://github.com/symfony/form/releases/tag/v5.3.8

 - nikic/php-parser updated from v4.12.0 to v4.13.0 minor
   See changes: nikic/PHP-Parser@v4.12.0...v4.13.0
   Release notes: https://github.com/nikic/PHP-Parser/releases/tag/v4.13.0

 - symfony/maker-bundle updated from v1.33.0 to v1.34.0 minor
   See changes: symfony/maker-bundle@v1.33.0...v1.34.0
   Release notes: https://github.com/symfony/maker-bundle/releases/tag/v1.34.0

 - symfony/phpunit-bridge updated from v5.3.7 to v5.3.8 patch
   See changes: symfony/phpunit-bridge@v5.3.7...v5.3.8
   Release notes: https://github.com/symfony/phpunit-bridge/releases/tag/v5.3.8

 - symfony/validator updated from v5.3.7 to v5.3.8 patch
   See changes: symfony/validator@v5.3.7...v5.3.8
   Release notes: https://github.com/symfony/validator/releases/tag/v5.3.8

 - symfony/web-profiler-bundle updated from v5.3.5 to v5.3.8 patch
   See changes: symfony/web-profiler-bundle@v5.3.5...v5.3.8
   Release notes: https://github.com/symfony/web-profiler-bundle/releases/tag/v5.3.8

### CODE REVIEW

**Review by damienalexandre — CHANGES_REQUESTED** [review]
Could you post a https://github.com/pyrech/composer-changelogs CHANGELOG ?

**Comment by Nispeon** [comment]
> Could you post a https://github.com/pyrech/composer-changelogs CHANGELOG ?

Added it to the commit message 😊

**Review by damienalexandre — APPROVED** [review]

**Comment by damienalexandre** [comment]
thanks. Could be nice to add it in the PR also, in case your commit is squashed!

**Comment by Nispeon** [comment]
Oh yeah for sure!

**Review by pyrech — APPROVED** [review]

**Pull request merged**
