### PR TITLE
Highlight target name in Secret Message to prevent confusion.

### LINKED ISSUE #119: Suggestion: display only ONE name in the "You have been chosen to gift X" message.
Hi there! 

[We](https://www.elao.com/) have been using Secret Santa for a couple of years now, and this year we encountered a "bug" or maybe more of a user experience failure: 

## The problem

This year, our Secret Santa admin received 2 gift instead of one, and __someone did't get a present__.

But it wasn't an algorithm failure, here's what happened:

- Once all is set, each player gets a `You've been chosen to gift X` message.
- The `X` being the tag name of the designated target.
- But this message also contain another name (that is automatically highlighted by Slack as well): the admin's tag name.
- One player simply identified the second name as their Secret Santa target. 
- So their real designated target didn't get anything*.

In an environment saturated by notifications of all kind, and with just a little bit of inattention, I think anyone could have make the same mistake. 
The very nature of _secret_ Santa made it impossible for us to identify there had been a confusion before the due date.

## My suggestion

Maybe, for this _critical_** message, don't mention the admin's name at all. 
Only display the target's name to prevent any confusion.

<br /><br />

Did anyone else experienced that problem? 
What do you think?

We would like to thank you all for that very important piece of software. 🎅🎄☃️

--- 

*: And yet they deserved it! They've been a very good person all year. 😢
**: Yeah... we're very serious about Christmas 😁

### PR DESCRIPTION
**Pull request by Tom32i**
This PR is a proposal to address the problem describer in #119 

- The target's tag name is highlighted by being in the center of the message.
- The administrator tag name remain but is moved to the footer.

Here's how it would look on Slack:

capture d ecran 2019-02-28 a 16 09 21

---

Fix #119

### CODE REVIEW

**Comment by Tom32i** [comment]
Please, let me now what you think of this proposal before I propagate the changes to the Discord MessageSender.

**Comment by damienalexandre** [comment]
Hey @Tom32i, thank again for taking the time to contribute, that's awesome.

Here are some thoughts about you change; we can discuss them if you want:

screenshot from 2019-03-01 19-05-16

May I suggest you to use the real app for testing? There is a convenient button:

image

Cheers

**Comment by pyrech** [comment]
Any news on this PR @Tom32i @damienalexandre ? Do you need some help ? :slightly_smiling_face:

**Comment by pyrech** [comment]
Closing as the private messages have just been refactored a bit to avoid confusion. Anyway thanks for your contribution :slightly_smiling_face:

**Pull request closed without merging**
